### PR TITLE
fallback to rhino if no default javascript is found .3 (lscproject#280)

### PR DESCRIPTION
**Pull request by artlog**
- avoid NullPointerException even if rhino and js are missing

### CODE REVIEW

**Comment by artlog** [comment]
update of #280 after previous review

**Comment by artlog** [comment]
previous review PR #292

**Comment by coudot** [comment]
Thanks @artlog!

@rouazana could you review it?

**Comment by abpai94** [comment]
@artlog I have pushed the fix to use java 8 compatible Optional code.

**Review by rouazana — APPROVED** [review]
Thank you for the changes!

**Pull request merged**
