### PR TITLE
Fix on asynchronous mode with a Novell Edirectory source

### PR DESCRIPTION
**Pull request by floriancaillet**
Hello,

I found a bug working in asynchronous mode with a Novell Edirectory source.

Error is Unexpected DecoderException: The length of controls must not be null.
This bug is known on apache.directory.api (https://issues.apache.org/jira/browse/DIRAPI-295) and has been fixed in 1.0.0 version of org.apache.directory.api api-all.

So I decide to update api-all from 1.0.0-M22 to 1.0.0.
There is an impact in JndiServices and SyncReplSourceService classes. And the project has to run in JAVA 1.8.

Do you think this fix could be integrated to new lsc version ?

Thanks,
Florian

### CODE REVIEW

**Comment by floriancaillet** [comment]
Without  these 2 xmlrpc dependencies, I can't build the project with maven (Which Maven repo did you use ?)
I don't test with JAVA 1.7, but it probably works. For sure it doesn't work in JAVA 1.6.

**Comment by soisik** [comment]
I'm using maven central. Could you send me your error log and tell me the maven & java version you use?

**Comment by floriancaillet** [comment]
Now I can build the project without these 2 xmlrpc dependencies changing my enterprise Maven Settings.
I 've just commited a new version of the pom.xml.

**Comment by soisik** [comment]
@coudot @rouazana please note that with this PR, LSC will not be supporting java 1.6 anymore (tests fails on java 1.6 while it works on current v2.1). Page https://lsc-project.org/documentation/latest/requirements will have to be updated. Maybe this should be merged into master, isn't v2.1 just for minor release ? Please advice. Otherwise I'm OK with this PR.

**Comment by rouazana** [comment]
I agree, for me we should not break compatibility in a minor release (even if nobody should use java 1.6).

**Comment by coudot** [comment]
Ok, in this case this PR should only be for LSC 2.2, but I hope we can release this major version in the next months.

**Comment by coudot** [comment]
See #106

**Pull request merged**
