### PR TITLE
Add missing letters in FrenchFilters (lsc #45)

### PR DESCRIPTION
**Pull request by coudot**

### CODE REVIEW

**Comment by coudot** [comment]
Indeed, maybe "FrenchFilters" is not a good class name.

What do you mean by UTF-8 capabilities?

**Comment by rouazana** [comment]
See for example https://stackoverflow.com/questions/15190656/easy-way-to-remove-utf-8-accents-from-a-string

**Comment by coudot** [comment]
Indeed, this would maybe be more efficient to use this instead our own replacement table

**Comment by coudot** [comment]
Ok, I'll do it

**Comment by coudot** [comment]
Test added

**Comment by soisik** [comment]
I'm going to merge, should I backport it to v2.1 ?

**Comment by coudot** [comment]
Yes please

**Comment by soisik** [comment]
Done : Merge in master + v2.1

**Pull request merged**
