### PR TITLE
Add github action

### PR DESCRIPTION
**Pull request by coudot**
See #237

### CODE REVIEW

**Comment by coudot** [comment]
I added another steps with JDK 11 but test with JDK 8 are failing with:
```
Warning:       [echo] Starting OpenDJ embedded server from /home/runner/work/lsc/lsc/target/test-classes
[INFO]      [java] Unrecognized option: --add-exports=java.base/sun.security.tools.keytool=ALL-UNNAMED
[INFO]      [java] Error: Could not create the Java Virtual Machine.
[INFO]      [java] Error: A fatal exception has occurred. Program will exit.
Error:       [java] Java Result: 1
Error: The operation was canceled.
```

Not sure it is linked to my modification. What do you think?

**Comment by coudot** [comment]
Same error after reverting the latest commit, should be linked to https://github.com/lsc-project/lsc/commit/2d47fa38fa09a5c7feb44fef1eae9372963a1613

Trying to run JDK 11 test before JDK 8 test to confirm this.

**Comment by coudot** [comment]
Seems we could use if/else in ant: https://ant.apache.org/manual/ifunless.html

@rouazana is this something you can look at?

**Comment by rouazana** [comment]
Strange, I tested the build with Java 8 without any issue.

I will have a look.

**Comment by rouazana** [comment]
It should be fixed, I will rebase your PR to check.

**Pull request merged**
