### PR TITLE
Values not removed from destination JDBC Database #80

### PR DESCRIPTION
**Pull request by MSSputnik**
Hi, 

here are my changes to fix this issue.
See file src/main/java/org/lsc/service/AbstractJdbcService.java

and a unit test to verify the issue:
See file: src/test/java/org/lsc/Ldap2JdbcSyncTest.java 

And I created a new sample application which has a similar setup with the configuration where I first hit the issue. I was missing this type of sample so I added it.
Maybe it was not the beast to integrate this sample in this pull request as well as it pollutes it.

Martin

### CODE REVIEW

**Comment by soisik** [comment]
Hi,

Thank you for your work and effort.

There are several problems with the unit test (I've run it with mvn clean package -Popendj)

Currently, getting "Failed tests:   testSyncLdap2Db(org.lsc.Ldap2JdbcSyncTest): testSyncLdap2Db - srcJndiServices missing".

This is because entry (cn=CN0001,ou=ldap2db2TestTask,ou=Test Data,dc=lsc-project,dc=org) has not been added to src/opendj/resources/org/lsc/opendj/test.ldif.

I commented this line, and got error on HSQLBN connection; Since ok after adding pc.setUrl("jdbc:hsqldb:file:target/hsqldb/lsc") to reloadConnections method.

Then got more error because of missing sample data in LDAP (ou=ldap2db2TestTask,ou=Test Data,dc=lsc-project,dc=org)

Could you make sure you have enclosed all necessarry file in this PR and tests do not fails ?

Also please fix indent. In org.lsc.Ldap2JdbcSyncTest, there are some code indented with spaces and some code indented with tabs.

Regards.

**Comment by MSSputnik** [comment]
Hi,
I corrected the intends and added the LDAP Server test content. I missed to update this file in the first commit.
My LDAP extension file is also renamed from 07-test.ldif to 07-inetOrgPersonExt.ldif to indicate the contents more clearly.

I decided to use a UUID as unique key and not a DN or Mail as this are subject to change and do not represent a good unique key. In case you do not like this idea for unit testing, I could change this. For my sample I like to keep it this way.

Unfortunately I have problems running the unit tests. The embedded opendj server does not start up, so my test are not 100% accurate. 
For the destination HSQL DB I changed the URL to a file source in the unit test as you suggested. I used a running stand alone HSQL Server before.

In case the tests still fail (I looks like they do) I will continue to investigate in about 8 days. I have no time earlier.

**Comment by soisik** [comment]
Hi Martin,

OpenDJ server doesn't start because of erroneous data in src/opendj/resources/org/lsc/opendj/test.ldif

```
ERROR org.lsc.opendj.LdapServer - org.opends.server.util.LDIFException: Unable to parse LDIF entry starting at line 230 because the first line does not contain a DN (the first line was "﻿dn: ou=ldap2db2TestTask,ou=Test Data,dc=lsc-project,dc=org" 
     [java] 09:10:12.734 [main] DEBUG org.lsc.opendj.LdapServer - o
```

Indeed, the file seems to contains some weird unicode at the beginning + M^ at the end of line
```
<U+FEFF>dn: ou=ldap2db2TestTask,ou=Test Data,dc=lsc-project,dc=org
telephoneNumber: +49-89-5293-79^M
^M
```

After removing these characters, the unit tests seems to complete with success. Could you fix the test data ?

**Comment by MSSputnik** [comment]
Hi,

I will change the Data when I'm back home in 8 days. Sorry for this delay.

Martin

Gesendet von IBM Verse


   Soisik Froger --- Re: [lsc-project/lsc] Values not removed from destination JDBC Database #80 (#81) --- 
    Von:"Soisik Froger" <notifications@github.com>An:"lsc-project/lsc" <lsc@noreply.github.com>Kopie:"Martin Schmidt" <martin.schmidt@bea-services.com>, "Author" <author@noreply.github.com>Datum:Mi. 26.06.2019 09:21Betreff:Re: [lsc-project/lsc] Values not removed from destination JDBC Database #80 (#81)
  
  Hi Martin, 
 OpenDJ server doesn't start because of erroneous data in src/opendj/resources/org/lsc/opendj/test.ldif 
 ERROR org.lsc.opendj.LdapServer - org.opends.server.util.LDIFException: Unable to parse LDIF entry starting at line 230 because the first line does not contain a DN (the first line was "﻿dn: ou=ldap2db2TestTask,ou=Test Data,dc=lsc-project,dc=org" 

     [java] 09:10:12.734 [main] DEBUG org.lsc.opendj.LdapServer - o

 
 Indeed, the file seems to contains some weird unicode at the beginning + M^ at the end of line 
 <U+FEFF>dn: ou=ldap2db2TestTask,ou=Test Data,dc=lsc-project,dc=org

telephoneNumber: +49-89-5293-79^M

^M

 
 After removing these characters, the unit tests seems to complete with success. Could you fix the test data ?

**Comment by coudot** [comment]
Thanks for your last commit @MSSputnik 

We will merge this pull request soon

**Pull request merged**
